---
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true

## Identifiants
elasticsearch.username: elkusername
elasticsearch.password: elkpassword
