---
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

## credentials
xpack.monitoring.enabled: false
xpack.monitoring.elasticsearch.username: elkusername
xpack.monitoring.elasticsearch.password: elkpassword
